//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSocialWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajePrivado
    {
        public MensajePrivado()
        {
            this.MensajePrivado1 = new HashSet<MensajePrivado>();
        }
    
        public int id { get; set; }
        public int idOrigen { get; set; }
        public int idDestino { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> idRespuesta { get; set; }
    
        public virtual ICollection<MensajePrivado> MensajePrivado1 { get; set; }
        public virtual MensajePrivado MensajePrivado2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
