//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSocialWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajePublico
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public string asunto { get; set; }
        public string texto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
